language: generic
sudo: required

services:
 - docker

# Build snap (in ubuntu yakkety container)
script:
 - docker run -v $(pwd):$(pwd) -t ubuntu:yakkety sh -c "cd $(pwd) && .travis/build.sh armhf"

# Decrypt snapcraft credentials
after_success:
 - .travis/decrypt.sh

# Snap deployment
deploy:
 # Master branch (edge)
 - provider: script
   skip_cleanup: true
   script:
    - docker run -v $(pwd):$(pwd) -t ubuntu:yakkety sh -c "cd $(pwd) && .travis/push.sh"
   on:
    branch: master

 # Tagged releases (channel detected)
 - provider: script
   skip_cleanup: true
   script:
    - docker run -v $(pwd):$(pwd) -t ubuntu:yakkety sh -c "cd $(pwd) && .travis/push.sh $TRAVIS_TAG"
   on:
    tags: true
